name: Build and Publish Docker Image

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION_TAG: latest

jobs:

  build-and-push-root-garfield:
    name: "ROOT and ROOT/Garfield++ images"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: pre-commit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rest-for-physics
          password: ${{ secrets.REST_DOCKER_PACKAGES_PUSH }}

      - name: Build root image
        uses: docker/build-push-action@v3
        with:
          context: base
          push: true
          pull: true
          target: root
          tags: |
            ghcr.io/rest-for-physics/root:${{ env.VERSION_TAG }}

      - name: Build root and garfield image
        uses: docker/build-push-action@v3
        with:
          context: base
          push: true
          pull: false
          target: root-garfield
          tags: |
            ghcr.io/rest-for-physics/root-garfield:${{ env.VERSION_TAG }}

  build-and-push-root-geant4:
    name: "Geant4 image"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build-and-push-root-garfield

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rest-for-physics
          password: ${{ secrets.REST_DOCKER_PACKAGES_PUSH }}

      - name: Build root and geant4 image without geant4 env variables
        uses: docker/build-push-action@v3
        with:
          context: base
          push: false
          pull: false
          target: geant4
          build-args: |
            USE_GARFIELD=""
          tags: |
            ghcr.io/rest-for-physics/root-geant4:${{ env.VERSION_TAG }}

      - name: Generate final base Dockerfile with Geant4 dataset environment variables
        run: |
          python3 base/scripts/geant4-dataset-dockerfile.py --image ghcr.io/rest-for-physics/root-geant4:${{ env.VERSION_TAG }} --output Dockerfile-root-geant4

      - name: Build and Push root-geant4 image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-root-geant4
          push: true
          pull: false
          tags: |
            ghcr.io/rest-for-physics/root-geant4:${{ env.VERSION_TAG }}


  build-and-push-root-garfield-geant4:
    name: "Geant4 image with Garfield++"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build-and-push-root-garfield

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rest-for-physics
          password: ${{ secrets.REST_DOCKER_PACKAGES_PUSH }}

      - name: Build root, garfield and geant4 image without geant4 env variables
        uses: docker/build-push-action@v3
        with:
          context: base
          push: false
          pull: false
          target: geant4
          tags: |
            ghcr.io/rest-for-physics/root-garfield-geant4:${{ env.VERSION_TAG }}

      - name: Generate final base Dockerfile with Geant4 dataset environment variables
        run: |
          python3 base/scripts/geant4-dataset-dockerfile.py --image ghcr.io/rest-for-physics/root-garfield-geant4:${{ env.VERSION_TAG }} --output Dockerfile-root-garfield-geant4

      - name: Build and Push root-garfield-geant4 image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-root-garfield-geant4
          push: true
          pull: false
          tags: |
            ghcr.io/rest-for-physics/root-garfield-geant4:${{ env.VERSION_TAG }}


  build-and-push-framework:
    name: "REST-for-Physics framework image"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build-and-push-root-garfield-geant4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rest-for-physics
          password: ${{ secrets.REST_DOCKER_PACKAGES_PUSH }}

      - name: Build and Push rest-for-physics framework image
        uses: docker/build-push-action@v3
        with:
          context: framework
          push: true
          pull: true
          tags: |
            ghcr.io/rest-for-physics/framework:latest
