name: Build and Publish Docker Image

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: rest-for-physics/base
  VERSION_TAG: latest

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  build-and-push-image:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    needs: pre-commit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rest-for-physics
          password: ${{ secrets.REST_DOCKER_PACKAGES_PUSH }}

      - name: Build parent to base image
        uses: docker/build-push-action@v3
        with:
          context: base
          push: false
          pull: false
          tags: |
            action/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}

      - name: Generate final base Dockerfile with Geant4 dataset environment variables
        run: |
          python3 base/scripts/geant4-dataset-dockerfile.py --image action/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }} --output Dockerfile-base-geant4-env

      - name: Build and Push base image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-base-geant4-env
          push: true
          pull: false
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}

      - name: Build and Push rest-for-physics framework image
        uses: docker/build-push-action@v3
        with:
          context: framework
          push: true
          pull: false
          tags: |
            ghcr.io/rest-for-physics/framework:latest
